// 中子态素压缩机
mods.avaritia.ExtremeCrafting.remove(<avaritia:neutronium_compressor>);
mods.avaritia.ExtremeCrafting.addShaped("COMPRESSOR", <avaritia:neutronium_compressor> * 1, 
[[<extrabotany:blockphotonium>, <extrabotany:blockphotonium>, <extrabotany:blockphotonium>, <ic2:te:38>, <ic2:te:38>, <ic2:te:38>, <extrabotany:blockphotonium>, <extrabotany:blockphotonium>, <extrabotany:blockphotonium>], 
[<ic2:crafting:4>, <avaritia:resource:1>, <avaritia:resource:4>, null, null, null, <avaritia:resource:4>, <avaritia:resource:1>, <ic2:crafting:4>],
[<extrabotany:blockphotonium>, <avaritia:resource:1>, <avaritia:resource:4>, null, null, null, <avaritia:resource:4>, <avaritia:resource:1>, <extrabotany:blockphotonium>],
[<ic2:crafting:4>, <avaritia:resource:1>, <avaritia:resource:4>, null, <avaritia:block_resource>, null, <avaritia:resource:4>, <avaritia:resource:1>, <ic2:crafting:4>],
[<minecraft:redstone_block>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:block_resource>, <avaritia:endest_pearl>, <avaritia:block_resource>, <avaritia:resource:4>, <avaritia:resource:4>, <minecraft:redstone_block>],
[<ic2:crafting:4>, <avaritia:resource:1>, <avaritia:resource:4>, null, <avaritia:block_resource>, null, <avaritia:resource:4>, <avaritia:resource:1>, <ic2:crafting:4>],
[<extrabotany:blockphotonium>, <avaritia:resource:1>, <avaritia:resource:4>, null, null, null, <avaritia:resource:4>, <avaritia:resource:1>, <extrabotany:blockphotonium>],
[<ic2:crafting:4>, <avaritia:resource:1>, <avaritia:resource:4>, null, null, null, <avaritia:resource:4>, <avaritia:resource:1>, <ic2:crafting:4>],
[<extrabotany:blockphotonium>, <extrabotany:blockphotonium>, <extrabotany:blockphotonium>, <ic2:crafting:4>, <extrabotany:blockphotonium>, <ic2:crafting:4>, <extrabotany:blockphotonium>, <extrabotany:blockphotonium>, <extrabotany:blockphotonium>]]);

// 中子态素收集器
mods.avaritia.ExtremeCrafting.remove(<avaritia:neutron_collector>);
mods.avaritia.ExtremeCrafting.addShaped("COLLECTOR", <avaritia:neutron_collector> * 1, 
[[<extrabotany:blockphotonium>, <extrabotany:blockphotonium>, <minecraft:obsidian>, <minecraft:obsidian>, <minecraft:obsidian>, <minecraft:obsidian>, <minecraft:obsidian>, <extrabotany:blockphotonium>, <extrabotany:blockphotonium>], 
[<extrabotany:blockphotonium>, <extrabotany:material:5>, <minecraft:obsidian>, <minecraft:obsidian>, <minecraft:obsidian>, <minecraft:obsidian>, <minecraft:obsidian>, <extrabotany:material:5>, <extrabotany:blockphotonium>],
[<extrabotany:blockphotonium>, <extrabotany:material:5>, <avaritia:resource:1>, <minecraft:redstone_block>, <minecraft:redstone_block>, <minecraft:redstone_block>, <avaritia:resource:1>, <extrabotany:material:5>, <extrabotany:blockphotonium>],
[<avaritia:resource:1>, <extrabotany:material:5>, <minecraft:redstone_block>, <minecraft:nether_star>, <advanced_solar_panels:machines:4>, <minecraft:nether_star>, <minecraft:redstone_block>, <extrabotany:material:5>, <avaritia:resource:1>],
[<extrabotany:blockphotonium>, <extrabotany:material:5>, <minecraft:redstone_block>, <advanced_solar_panels:machines:4>, <minecraft:emerald>, <advanced_solar_panels:machines:4>, <minecraft:redstone_block>, <extrabotany:material:5>, <extrabotany:blockphotonium>],
[<avaritia:resource:1>, <extrabotany:material:5>, <minecraft:redstone_block>, <minecraft:nether_star>, <advanced_solar_panels:machines:4>, <minecraft:nether_star>, <minecraft:redstone_block>, <extrabotany:material:5>, <avaritia:resource:1>],
[<extrabotany:blockphotonium>, <extrabotany:material:5>, <avaritia:resource:1>, <minecraft:redstone_block>, <minecraft:redstone_block>, <minecraft:redstone_block>, <avaritia:resource:1>, <extrabotany:material:5>, <extrabotany:blockphotonium>],
[<extrabotany:blockphotonium>, <extrabotany:material:5>, <extrabotany:material:5>, <extrabotany:material:5>, <extrabotany:material:5>, <extrabotany:material:5>, <extrabotany:material:5>, <extrabotany:material:5>, <extrabotany:blockphotonium>],
[<extrabotany:blockphotonium>, <extrabotany:blockphotonium>, <extrabotany:blockphotonium>, <avaritia:resource:1>, <extrabotany:blockphotonium>, <avaritia:resource:1>, <extrabotany:blockphotonium>, <extrabotany:blockphotonium>, <extrabotany:blockphotonium>]]);

// 昴星团战斗女仆
recipes.remove(<extrabotany:combatmaidhelm>);
recipes.remove(<extrabotany:combatmaidboots>);
recipes.remove(<extrabotany:combatmaidlegs>);
recipes.remove(<extrabotany:combatmaidchest>);
mods.avaritia.ExtremeCrafting.addShaped("COMBATNAIDLEGS", <extrabotany:combatmaidlegs> * 1, 
[[<botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"})], [<botania:specialflower>.withTag({type: "stardustlotus"}), <ic2:crafting:4>, <extrabotany:shadowwarriorlegs>.withTag({isnight: 0 as byte}), <ic2:quantum_leggings>.anyDamage(), <botania:terrasteellegs>, <botania:elementiumlegs>, <extrabotany:goblinslayerlegs>.withTag({isday: 0 as byte}), <ic2:crafting:4>, <botania:specialflower>.withTag({type: "stardustlotus"})],[<botania:specialflower>.withTag({type: "reikarlily"}), <avaritia:ultimate_stew> * 9, null, null, null, null, null, <avaritia:ultimate_stew> * 9, <botania:specialflower>.withTag({type: "reikarlily"})],[<botania:specialflower>.withTag({type: "stardustlotus"}), null, null, <botania:manaresource:14>, <botania:manaresource:14>, <botania:manaresource:14>, null, null, <botania:specialflower>.withTag({type: "stardustlotus"})],[<botania:specialflower>.withTag({type: "reikarlily"}), null, null, <extrabotany:material:7>, <botania:terrasteellegs>, <extrabotany:material:7>, null, null, <botania:specialflower>.withTag({type: "reikarlily"})],[<botania:specialflower>.withTag({type: "stardustlotus"}), null, null, <extrabotany:material:7>, null, <extrabotany:material:7>, null, null, <botania:specialflower>.withTag({type: "stardustlotus"})],[<botania:specialflower>.withTag({type: "reikarlily"}), <avaritia:ultimate_stew> * 9, null, null, null, null, null, <avaritia:ultimate_stew> * 9, <botania:specialflower>.withTag({type: "reikarlily"})],[<botania:specialflower>.withTag({type: "stardustlotus"}), <extrabotany:blockshadowium>, <botania:storage>, <extrabotany:blockphotonium>, <botania:storage:2>, <minecraft:gold_block>, <botania:storage:3>, <botania:storage:1>, <botania:specialflower>.withTag({type: "stardustlotus"})],[<botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"})]]);
mods.avaritia.ExtremeCrafting.addShaped("COMBATNAIDLEGSBOOTS", <extrabotany:combatmaidboots> * 1, 
[[<botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"})], [<botania:specialflower>.withTag({type: "stardustlotus"}), <ic2:crafting:4>, <extrabotany:shadowwarriorboots>.withTag({isnight: 0 as byte}), <ic2:quantum_boots>.anyDamage(), <botania:terrasteelboots>, <botania:elementiumboots>, <extrabotany:goblinslayerboots>.withTag({isday: 0 as byte}), <ic2:crafting:4>, <botania:specialflower>.withTag({type: "stardustlotus"})],[<botania:specialflower>.withTag({type: "reikarlily"}), <avaritia:ultimate_stew> * 9, null, null, null, null, null, <avaritia:ultimate_stew> * 9, <botania:specialflower>.withTag({type: "reikarlily"})],[<botania:specialflower>.withTag({type: "stardustlotus"}), null, null, <extrabotany:material:7>, null, <extrabotany:material:7>, null, null, <botania:specialflower>.withTag({type: "stardustlotus"})],[<botania:specialflower>.withTag({type: "reikarlily"}), null, null, <extrabotany:material:7>, <botania:terrasteelboots>, <extrabotany:material:7>, null, null, <botania:specialflower>.withTag({type: "reikarlily"})],[<botania:specialflower>.withTag({type: "stardustlotus"}), null, null, <botania:manaresource:14>, <botania:manaresource:14>, <botania:manaresource:14>, null, null, <botania:specialflower>.withTag({type: "stardustlotus"})],[<botania:specialflower>.withTag({type: "reikarlily"}), <avaritia:ultimate_stew> * 9, null, null, null, null, null, <avaritia:ultimate_stew> * 9, <botania:specialflower>.withTag({type: "reikarlily"})],[<botania:specialflower>.withTag({type: "stardustlotus"}), <extrabotany:blockshadowium>, <botania:storage>, <extrabotany:blockphotonium>, <botania:storage:2>, <minecraft:gold_block>, <botania:storage:3>, <botania:storage:1>, <botania:specialflower>.withTag({type: "stardustlotus"})],[<botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"})]]);
mods.avaritia.ExtremeCrafting.addShaped("COMBATNAIDLEGSHELM", <extrabotany:combatmaidhelm> * 1, 
[[<botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"})], [<botania:specialflower>.withTag({type: "stardustlotus"}), <ic2:crafting:4>, <extrabotany:shadowwarriorhelm>.withTag({isnight: 0 as byte}), <ic2:quantum_helmet>.anyDamage(), <botania:terrasteelhelm>, <botania:elementiumhelm>, <extrabotany:goblinslayerhelm>.withTag({isday: 0 as byte}), <ic2:crafting:4>, <botania:specialflower>.withTag({type: "stardustlotus"})],[<botania:specialflower>.withTag({type: "reikarlily"}), <avaritia:ultimate_stew> * 9, null, null, null, null, null, <avaritia:ultimate_stew> * 9, <botania:specialflower>.withTag({type: "reikarlily"})],[<botania:specialflower>.withTag({type: "stardustlotus"}), null, null, <extrabotany:material:7>, null, <extrabotany:material:7>, null, null, <botania:specialflower>.withTag({type: "stardustlotus"})],[<botania:specialflower>.withTag({type: "reikarlily"}), null, null, <botania:manaresource:14>, <botania:manaresource:14>, <botania:manaresource:14>, null, null, <botania:specialflower>.withTag({type: "reikarlily"})],[<botania:specialflower>.withTag({type: "stardustlotus"}), null, null, <extrabotany:material:7>, <botania:terrasteelhelm>, <extrabotany:material:7>, null, null, <botania:specialflower>.withTag({type: "stardustlotus"})],[<botania:specialflower>.withTag({type: "reikarlily"}), <avaritia:ultimate_stew> * 9, null, null, null, null, null, <avaritia:ultimate_stew> * 9, <botania:specialflower>.withTag({type: "reikarlily"})],[<botania:specialflower>.withTag({type: "stardustlotus"}), <extrabotany:blockshadowium>, <botania:storage>, <extrabotany:blockphotonium>, <botania:storage:2>, <minecraft:gold_block>, <botania:storage:3>, <botania:storage:1>, <botania:specialflower>.withTag({type: "stardustlotus"})],[<botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"})]]);
mods.avaritia.ExtremeCrafting.addShaped("COMBATNAIDLEGSCHEST", <extrabotany:combatmaidchest> * 1, 
[[<botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"})], [<botania:specialflower>.withTag({type: "stardustlotus"}), <ic2:crafting:4>, <extrabotany:shadowwarriorchest>.withTag({isnight: 0 as byte}), <ic2:quantum_chestplate>.anyDamage(), <botania:terrasteelchest>, <botania:elementiumchest>, <extrabotany:goblinslayerchest>.withTag({isday: 0 as byte}), <ic2:crafting:4>, <botania:specialflower>.withTag({type: "stardustlotus"})],[<botania:specialflower>.withTag({type: "reikarlily"}), <avaritia:ultimate_stew> * 9, null, null, null, null, null, <avaritia:ultimate_stew> * 9, <botania:specialflower>.withTag({type: "reikarlily"})],[<botania:specialflower>.withTag({type: "stardustlotus"}), null, null, <extrabotany:material:7>, null, <extrabotany:material:7>, null, null, <botania:specialflower>.withTag({type: "stardustlotus"})],[<botania:specialflower>.withTag({type: "reikarlily"}), null, null, <extrabotany:material:7>, <botania:terrasteelchest>, <extrabotany:material:7>, null, null, <botania:specialflower>.withTag({type: "reikarlily"})],[<botania:specialflower>.withTag({type: "stardustlotus"}), null, null, <botania:manaresource:14>, <botania:manaresource:14>, <botania:manaresource:14>, null, null, <botania:specialflower>.withTag({type: "stardustlotus"})],[<botania:specialflower>.withTag({type: "reikarlily"}), <avaritia:ultimate_stew> * 9, null, null, null, null, null, <avaritia:ultimate_stew> * 9, <botania:specialflower>.withTag({type: "reikarlily"})],[<botania:specialflower>.withTag({type: "stardustlotus"}), <extrabotany:blockshadowium>, <botania:storage>, <extrabotany:blockphotonium>, <botania:storage:2>, <minecraft:gold_block>, <botania:storage:3>, <botania:storage:1>, <botania:specialflower>.withTag({type: "stardustlotus"})],[<botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"})]]);

// 星空歌姬
recipes.remove(<extrabotany:cosmeticmaidlegs>);
recipes.remove(<extrabotany:cosmeticmaidboots>);
recipes.remove(<extrabotany:cosmeticmaidhelm>);
recipes.remove(<extrabotany:cosmeticmaidchest>);
mods.avaritia.ExtremeCrafting.addShaped("COSMETICMAIDLEGS", <extrabotany:cosmeticmaidlegs> * 1, 
[[<botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"})], [<botania:specialflower>.withTag({type: "stardustlotus"}), <ic2:crafting:4>, <extrabotany:shadowwarriorlegs>.withTag({isnight: 0 as byte}), <ic2:quantum_leggings>.anyDamage(), <botania:terrasteellegs>, <botania:elementiumlegs>, <extrabotany:goblinslayerlegs>.withTag({isday: 0 as byte}), <ic2:crafting:4>, <botania:specialflower>.withTag({type: "stardustlotus"})],[<botania:specialflower>.withTag({type: "reikarlily"}), <avaritia:ultimate_stew> * 9, null, null, null, null, null, <avaritia:ultimate_stew> * 9, <botania:specialflower>.withTag({type: "reikarlily"})],[<botania:specialflower>.withTag({type: "stardustlotus"}), null, null, <botania:manaresource:14>, <botania:manaresource:14>, <botania:manaresource:14>, null, null, <botania:specialflower>.withTag({type: "stardustlotus"})],[<botania:specialflower>.withTag({type: "reikarlily"}), null, null, <extrabotany:material:7>, <botania:manasteellegs>, <extrabotany:material:7>, null, null, <botania:specialflower>.withTag({type: "reikarlily"})],[<botania:specialflower>.withTag({type: "stardustlotus"}), null, null, <extrabotany:material:7>, null, <extrabotany:material:7>, null, null, <botania:specialflower>.withTag({type: "stardustlotus"})],[<botania:specialflower>.withTag({type: "reikarlily"}), <avaritia:ultimate_stew> * 9, null, null, null, null, null, <avaritia:ultimate_stew> * 9, <botania:specialflower>.withTag({type: "reikarlily"})],[<botania:specialflower>.withTag({type: "stardustlotus"}), <extrabotany:blockshadowium>, <botania:storage>, <extrabotany:blockphotonium>, <botania:storage:2>, <minecraft:gold_block>, <botania:storage:3>, <botania:storage:1>, <botania:specialflower>.withTag({type: "stardustlotus"})],[<botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"})]]);
mods.avaritia.ExtremeCrafting.addShaped("COSMETICMAIDBOOTS", <extrabotany:cosmeticmaidboots> * 1, 
[[<botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"})], [<botania:specialflower>.withTag({type: "stardustlotus"}), <ic2:crafting:4>, <extrabotany:shadowwarriorboots>.withTag({isnight: 0 as byte}), <ic2:quantum_boots>.anyDamage(), <botania:terrasteelboots>, <botania:elementiumboots>, <extrabotany:goblinslayerboots>.withTag({isday: 0 as byte}), <ic2:crafting:4>, <botania:specialflower>.withTag({type: "stardustlotus"})],[<botania:specialflower>.withTag({type: "reikarlily"}), <avaritia:ultimate_stew> * 9, null, null, null, null, null, <avaritia:ultimate_stew> * 9, <botania:specialflower>.withTag({type: "reikarlily"})],[<botania:specialflower>.withTag({type: "stardustlotus"}), null, null, <extrabotany:material:7>, null, <extrabotany:material:7>, null, null, <botania:specialflower>.withTag({type: "stardustlotus"})],[<botania:specialflower>.withTag({type: "reikarlily"}), null, null, <extrabotany:material:7>, <botania:manasteelboots>, <extrabotany:material:7>, null, null, <botania:specialflower>.withTag({type: "reikarlily"})],[<botania:specialflower>.withTag({type: "stardustlotus"}), null, null, <botania:manaresource:14>, <botania:manaresource:14>, <botania:manaresource:14>, null, null, <botania:specialflower>.withTag({type: "stardustlotus"})],[<botania:specialflower>.withTag({type: "reikarlily"}), <avaritia:ultimate_stew> * 9, null, null, null, null, null, <avaritia:ultimate_stew> * 9, <botania:specialflower>.withTag({type: "reikarlily"})],[<botania:specialflower>.withTag({type: "stardustlotus"}), <extrabotany:blockshadowium>, <botania:storage>, <extrabotany:blockphotonium>, <botania:storage:2>, <minecraft:gold_block>, <botania:storage:3>, <botania:storage:1>, <botania:specialflower>.withTag({type: "stardustlotus"})],[<botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"})]]);
mods.avaritia.ExtremeCrafting.addShaped("COSMETICMAIDHELM", <extrabotany:cosmeticmaidhelm> * 1, 
[[<botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"})], [<botania:specialflower>.withTag({type: "stardustlotus"}), <ic2:crafting:4>, <extrabotany:shadowwarriorhelm>.withTag({isnight: 0 as byte}), <ic2:quantum_helmet>.anyDamage(), <botania:terrasteelhelm>, <botania:elementiumhelm>, <extrabotany:goblinslayerhelm>.withTag({isday: 0 as byte}), <ic2:crafting:4>, <botania:specialflower>.withTag({type: "stardustlotus"})],[<botania:specialflower>.withTag({type: "reikarlily"}), <avaritia:ultimate_stew> * 9, null, null, null, null, null, <avaritia:ultimate_stew> * 9, <botania:specialflower>.withTag({type: "reikarlily"})],[<botania:specialflower>.withTag({type: "stardustlotus"}), null, null, <extrabotany:material:7>, null, <extrabotany:material:7>, null, null, <botania:specialflower>.withTag({type: "stardustlotus"})],[<botania:specialflower>.withTag({type: "reikarlily"}), null, null, <botania:manaresource:14>, <botania:manaresource:14>, <botania:manaresource:14>, null, null, <botania:specialflower>.withTag({type: "reikarlily"})],[<botania:specialflower>.withTag({type: "stardustlotus"}), null, null, <extrabotany:material:7>, <botania:manasteelhelm>, <extrabotany:material:7>, null, null, <botania:specialflower>.withTag({type: "stardustlotus"})],[<botania:specialflower>.withTag({type: "reikarlily"}), <avaritia:ultimate_stew> * 9, null, null, null, null, null, <avaritia:ultimate_stew> * 9, <botania:specialflower>.withTag({type: "reikarlily"})],[<botania:specialflower>.withTag({type: "stardustlotus"}), <extrabotany:blockshadowium>, <botania:storage>, <extrabotany:blockphotonium>, <botania:storage:2>, <minecraft:gold_block>, <botania:storage:3>, <botania:storage:1>, <botania:specialflower>.withTag({type: "stardustlotus"})],[<botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"})]]);
mods.avaritia.ExtremeCrafting.addShaped("COSMETICMAIDCHEST", <extrabotany:cosmeticmaidchest> * 1, 
[[<botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"})], [<botania:specialflower>.withTag({type: "stardustlotus"}), <ic2:crafting:4>, <extrabotany:shadowwarriorchest>.withTag({isnight: 0 as byte}), <ic2:quantum_chestplate>.anyDamage(), <botania:terrasteelchest>, <botania:elementiumchest>, <extrabotany:goblinslayerchest>.withTag({isday: 0 as byte}), <ic2:crafting:4>, <botania:specialflower>.withTag({type: "stardustlotus"})],[<botania:specialflower>.withTag({type: "reikarlily"}), <avaritia:ultimate_stew> * 9, null, null, null, null, null, <avaritia:ultimate_stew> * 9, <botania:specialflower>.withTag({type: "reikarlily"})],[<botania:specialflower>.withTag({type: "stardustlotus"}), null, null, <extrabotany:material:7>, null, <extrabotany:material:7>, null, null, <botania:specialflower>.withTag({type: "stardustlotus"})],[<botania:specialflower>.withTag({type: "reikarlily"}), null, null, <extrabotany:material:7>, <botania:manasteelchest>, <extrabotany:material:7>, null, null, <botania:specialflower>.withTag({type: "reikarlily"})],[<botania:specialflower>.withTag({type: "stardustlotus"}), null, null, <botania:manaresource:14>, <botania:manaresource:14>, <botania:manaresource:14>, null, null, <botania:specialflower>.withTag({type: "stardustlotus"})],[<botania:specialflower>.withTag({type: "reikarlily"}), <avaritia:ultimate_stew> * 9, null, null, null, null, null, <avaritia:ultimate_stew> * 9, <botania:specialflower>.withTag({type: "reikarlily"})],[<botania:specialflower>.withTag({type: "stardustlotus"}), <extrabotany:blockshadowium>, <botania:storage>, <extrabotany:blockphotonium>, <botania:storage:2>, <minecraft:gold_block>, <botania:storage:3>, <botania:storage:1>, <botania:specialflower>.withTag({type: "stardustlotus"})],[<botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"}), <botania:specialflower>.withTag({type: "stardustlotus"}), <botania:specialflower>.withTag({type: "reikarlily"})]]);


// 贤者之石
recipes.remove(<projecte:item.pe_philosophers_stone>);
mods.avaritia.ExtremeCrafting.addShaped("NAMEPLACEHOLDER1", <projecte:item.pe_philosophers_stone> * 1, [[<enderio:block_alloy_endergy:3>, <extrabotany:material:1>, <extrabotany:material:1>, <botania:storage:1>, <extrabotany:material:1>, <extrabotany:material:1>, <enderio:block_alloy_endergy:3>, null, null], [<extrabotany:material:1>, <ic2:crafting:4>, <ic2:crafting:4>, <mekanism:controlcircuit:3>, <ic2:crafting:4>, <ic2:crafting:4>, <extrabotany:material:1>, null, null],[<extrabotany:material:1>, <ic2:crafting:4>, <extrautils2:opinium:5>, <botania:terraplate>, <extrautils2:opinium:5>, <ic2:crafting:4>, <extrabotany:material:1>, null, null],[<botania:storage:1>, <mekanism:controlcircuit:3>, <enderio:item_capacitor_melodic>, <advanced_solar_panels:crafting:12>, <enderio:item_capacitor_melodic>, <mekanism:controlcircuit:3>, <botania:storage:1>, null, null],[<extrabotany:material:1>, <ic2:crafting:4>, <extrautils2:opinium:5>, <botania:terraplate>, <extrautils2:opinium:5>, <ic2:crafting:4>, <extrabotany:material:1>, null, null],[<extrabotany:material:1>, <ic2:crafting:4>, <ic2:crafting:4>, <mekanism:controlcircuit:3>, <ic2:crafting:4>, <ic2:crafting:4>, <extrabotany:material:1>, null, null],[<enderio:block_alloy_endergy:3>, <extrabotany:material:1>, <extrabotany:material:1>, <botania:storage:1>, <extrabotany:material:1>, <extrabotany:material:1>, <enderio:block_alloy_endergy:3>, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null]]);

// 转化桌
recipes.remove(<projecte:transmutation_table>);
mods.avaritia.ExtremeCrafting.addShaped("NAMEPLACEHOLDER2", <projecte:transmutation_table> * 1, [[<enderio:block_alloy_endergy:3>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:4>, <avaritia:resource:4>, <enderio:block_alloy_endergy:3>, null, null], [<avaritia:resource:4>, <enderio:item_capacitor_melodic>, <avaritia:resource:0>, <avaritia:resource:5>, <avaritia:resource:0>, <enderio:item_capacitor_melodic>, <avaritia:resource:4>, null, null],[<avaritia:resource:4>, <extrabotany:material:1>, <extrautils2:opinium:5>, <advanced_solar_panels:crafting:12>, <extrautils2:opinium:5>, <extrabotany:material:1>, <avaritia:resource:4>, null, null],[<avaritia:resource:6>, <extrabotany:material:1>, <advanced_solar_panels:crafting:12>, <projecte:item.pe_philosophers_stone>, <advanced_solar_panels:crafting:12>, <extrabotany:material:1>, <avaritia:resource:6>, null, null],[<avaritia:resource:4>, <extrabotany:material:1>, <extrautils2:opinium:5>, <advanced_solar_panels:crafting:12>, <extrautils2:opinium:5>, <extrabotany:material:1>, <avaritia:resource:4>, null, null],[<avaritia:resource:4>, <enderio:item_capacitor_melodic>, <extrabotany:material:1>, <extrabotany:material:1>, <extrabotany:material:1>, <enderio:item_capacitor_melodic>, <avaritia:resource:4>, null, null],[<enderio:block_alloy_endergy:3>, <avaritia:resource:4>, <avaritia:resource:4>, <avaritia:resource:6>, <avaritia:resource:4>, <avaritia:resource:4>, <enderio:block_alloy_endergy:3>, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null]]);

// 天使指环
recipes.remove(<extrautils2:angelring:1>);
mods.avaritia.ExtremeCrafting.addShaped("NAMEPLACEHOLDER3", <extrautils2:angelring:1> * 1, [[<enderio:block_alloy_endergy:3>, <enderio:item_alloy_endergy_ingot:2>, <enderio:item_alloy_endergy_ingot:2>, <extrabotany:material:1>, <enderio:item_alloy_endergy_ingot:2>, <enderio:item_alloy_endergy_ingot:2>, <enderio:block_alloy_endergy:3>, null, null], [<enderio:item_alloy_endergy_ingot:2>, <botania:storage:1>, <enderio:item_capacitor_melodic>, <thermalfoundation:storage_alloy:7>, <enderio:item_capacitor_melodic>, <botania:storage:1>, <enderio:item_alloy_endergy_ingot:2>, null, null],[<enderio:item_alloy_endergy_ingot:2>, <enderio:item_capacitor_melodic>, <ic2:crafting:4>, <extrabotany:material:1>, <ic2:crafting:4>, <enderio:item_capacitor_melodic>, <enderio:item_alloy_endergy_ingot:2>, null, null],[<extrabotany:material:1>, <thermalfoundation:storage_alloy:7>, <extrabotany:material:1>, <extrautils2:chickenring:1>, <extrabotany:material:1>, <thermalfoundation:storage_alloy:7>, <extrabotany:material:1>, null, null],[<enderio:item_alloy_endergy_ingot:2>, <enderio:item_capacitor_melodic>, <ic2:crafting:4>, <extrabotany:material:1>, <ic2:crafting:4>, <enderio:item_capacitor_melodic>, <enderio:item_alloy_endergy_ingot:2>, null, null],[<enderio:item_alloy_endergy_ingot:2>, <botania:storage:1>, <enderio:item_capacitor_melodic>, <thermalfoundation:storage_alloy:7>, <enderio:item_capacitor_melodic>, <botania:storage:1>, <enderio:item_alloy_endergy_ingot:2>, null, null],[<enderio:block_alloy_endergy:3>, <enderio:item_alloy_endergy_ingot:2>, <enderio:item_alloy_endergy_ingot:2>, <extrabotany:material:1>, <enderio:item_alloy_endergy_ingot:2>, <enderio:item_alloy_endergy_ingot:2>, <enderio:block_alloy_endergy:3>, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null]]);

// 能量注入器
recipes.remove(<draconicevolution:energy_infuser>);
mods.avaritia.ExtremeCrafting.addShaped("NAMEPLACEHOLDER4", <draconicevolution:energy_infuser> * 1, [[<enderio:block_alloy_endergy:3>, <thermalfoundation:storage_alloy:7>, <thermalfoundation:storage_alloy:7>, <botania:storage:1>, <thermalfoundation:storage_alloy:7>, <thermalfoundation:storage_alloy:7>, <enderio:block_alloy_endergy:3>, null, null], [<thermalfoundation:storage_alloy:7>, <draconicevolution:draconic_core>, <draconicevolution:draconic_core>, <draconicevolution:energy_storage_core>, <draconicevolution:draconic_core>, <draconicevolution:draconic_core>, <thermalfoundation:storage_alloy:7>, null, null],[<thermalfoundation:storage_alloy:7>, <draconicevolution:draconic_core>, <draconicevolution:particle_generator:0>, <extrautils2:opinium:5>, <draconicevolution:particle_generator:0>, <draconicevolution:draconic_core>, <thermalfoundation:storage_alloy:7>, null, null],[<botania:storage:1>, <draconicevolution:energy_storage_core>, <extrautils2:opinium:5>, <botania:terraplate>, <extrautils2:opinium:5>, <draconicevolution:energy_storage_core>, <botania:storage:1>, null, null],[<thermalfoundation:storage_alloy:7>, <draconicevolution:draconic_core>, <draconicevolution:particle_generator:0>, <extrautils2:opinium:5>, <draconicevolution:particle_generator:0>, <draconicevolution:draconic_core>, <thermalfoundation:storage_alloy:7>, null, null],[<thermalfoundation:storage_alloy:7>, <draconicevolution:draconic_core>, <draconicevolution:draconic_core>, <draconicevolution:energy_storage_core>, <draconicevolution:draconic_core>, <draconicevolution:draconic_core>, <thermalfoundation:storage_alloy:7>, null, null],[<enderio:block_alloy_endergy:3>, <thermalfoundation:storage_alloy:7>, <thermalfoundation:storage_alloy:7>, <botania:storage:1>, <thermalfoundation:storage_alloy:7>, <thermalfoundation:storage_alloy:7>, <enderio:block_alloy_endergy:3>, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null]]);

// 神龙之力权杖
recipes.remove(<draconicevolution:draconic_staff_of_power>);
mods.avaritia.ExtremeCrafting.addShaped("NAMEPLACEHOLDER5", <draconicevolution:draconic_staff_of_power> * 1, [[<enderio:block_alloy_endergy:3>, <enderio:block_alloy_endergy:3>, <projecte:matter_block:1>, <projecte:matter_block:1>, <projecte:matter_block:0>, <projecte:matter_block:1>, <projecte:matter_block:1>, <enderio:block_alloy_endergy:3>, <enderio:block_alloy_endergy:3>], [<draconicevolution:wyvern_core>, <advanced_solar_panels:crafting:5>, <avaritia:resource:6>, <draconicevolution:draconic_axe>, <draconicevolution:draconic_pick>, <draconicevolution:draconic_shovel>, <avaritia:resource:6>, <advanced_solar_panels:crafting:5>, <draconicevolution:wyvern_core>],[null, <advanced_solar_panels:crafting:5>, <enderio:item_capacitor_melodic>, <extracells:storage.component:2>, <draconicevolution:draconic_sword>, <extracells:storage.component:2>, <enderio:item_capacitor_melodic>, <advanced_solar_panels:crafting:5>, null],[null, <advanced_solar_panels:crafting:5>, <avaritia:resource:6>, <draconicevolution:draconic_block>, <draconicevolution:awakened_core>, <draconicevolution:draconic_block>, <avaritia:resource:6>, <advanced_solar_panels:crafting:5>, null],[null, <advanced_solar_panels:crafting:5>, <avaritia:resource:6>, <draconicevolution:draconic_block>, <draconicevolution:draconic_energy_core>, <draconicevolution:draconic_block>, <avaritia:resource:6>, <advanced_solar_panels:crafting:5>, null],[null, <advanced_solar_panels:crafting:5>, <draconicevolution:draconic_block>, <extrabotany:excaliber>, <projecte:item.pe_rm_sword>, <extrabotany:excaliber>, <draconicevolution:draconic_block>, <advanced_solar_panels:crafting:5>, null],[null, null, null, <enderio:item_capacitor_totemic>, <enderio:block_alloy_endergy:3>, <enderio:item_capacitor_totemic>, null, null, null],[null, null, null, <draconicevolution:draconic_block>, <enderio:block_alloy_endergy:3>, <draconicevolution:draconic_block>, null, null, null],[null, null, null, null, <draconicevolution:awakened_core>, null, null, null, null]]);

// 神龙头盔
recipes.remove(<draconicevolution:draconic_helm>);
mods.avaritia.ExtremeCrafting.addShaped("NAMEPLACEHOLDER6", <draconicevolution:draconic_helm> * 1, [[<draconicevolution:draconic_block>, <draconicevolution:draconic_block>, <draconicevolution:draconium_block:0>, <draconicevolution:draconium_block:0>, <draconicevolution:draconium_block:0>, <draconicevolution:draconium_block:0>, <draconicevolution:draconium_block:0>, <draconicevolution:draconic_block>, <draconicevolution:draconic_block>], [null, <advanced_solar_panels:crafting:5>, <avaritia:resource:6>, <projecte:item.pe_gem_armor_3>, <advanced_solar_panels:ultimatesolarhelmet>, <enderio:item_stellar_alloy_helmet>, <avaritia:resource:6>, <advanced_solar_panels:crafting:5>, null],[null, <advanced_solar_panels:crafting:5>, null, <extracells:storage.component:2>, <extrautils2:opinium:8>, <extracells:storage.component:2>, null, <advanced_solar_panels:crafting:5>, null],[null, <advanced_solar_panels:crafting:5>, <avaritia:resource:6>, <draconicevolution:draconic_block>, <draconicevolution:awakened_core>, <draconicevolution:draconic_block>, <avaritia:resource:6>, <advanced_solar_panels:crafting:5>, null],[null, <advanced_solar_panels:crafting:5>, <avaritia:resource:6>, <draconicevolution:draconic_block>, <draconicevolution:draconic_energy_core>, <draconicevolution:draconic_block>, <avaritia:resource:6>, <advanced_solar_panels:crafting:5>, null],[null, <advanced_solar_panels:crafting:5>, <draconicevolution:draconium_block:0>, null, <mysticalagriculture:supremium_helmet>, null, <draconicevolution:draconium_block:0>, <advanced_solar_panels:crafting:5>, null],[null, <draconicevolution:draconic_block>, <draconicevolution:draconium_block:0>, null, <draconicevolution:wyvern_helm>, null, <draconicevolution:draconium_block:0>, <draconicevolution:draconic_block>, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null]]);

// 双足飞龙头盔
recipes.remove(<draconicevolution:wyvern_helm>);
mods.avaritia.ExtremeCrafting.addShaped("NAMEPLACEHOLDER7", <draconicevolution:wyvern_helm> * 1, [[<draconicevolution:draconium_block:0>, null, <draconicevolution:draconium_block:0>, <draconicevolution:draconium_block:0>, <draconicevolution:draconium_block:0>, <draconicevolution:draconium_block:0>, <draconicevolution:draconium_block:0>, null, <draconicevolution:draconium_block:0>], [null, <advanced_solar_panels:crafting:2>, <extrautils2:opinium:8>, <projecte:item.pe_rm_armor_3>, <enderio:item_end_steel_helmet>, <ic2:nano_helmet>, <extrautils2:opinium:8>, <advanced_solar_panels:crafting:2>, null],[null, <advanced_solar_panels:crafting:2>, null, <extracells:storage.component:2>, <avaritia:resource:4>, <extracells:storage.component:2>, null, <advanced_solar_panels:crafting:2>, null],[null, <advanced_solar_panels:crafting:2>, <extrautils2:opinium:8>, <draconicevolution:draconium_block:0>, <draconicevolution:wyvern_core>, <draconicevolution:draconium_block:0>, <extrautils2:opinium:8>, <advanced_solar_panels:crafting:2>, null],[null, <advanced_solar_panels:crafting:2>, <extrautils2:opinium:8>, <draconicevolution:draconium_block:0>, <draconicevolution:wyvern_energy_core>, <draconicevolution:draconium_block:0>, <extrautils2:opinium:8>, <advanced_solar_panels:crafting:2>, null],[null, <advanced_solar_panels:crafting:2>, <draconicevolution:draconium_block:0>, null, <botania:terrasteelhelm>, null, <draconicevolution:draconium_block:0>, <advanced_solar_panels:crafting:2>, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null]]);

// 神龙护腿
recipes.remove(<draconicevolution:draconic_legs>);
mods.avaritia.ExtremeCrafting.addShaped("NAMEPLACEHOLDER8", <draconicevolution:draconic_legs> * 1, [[<draconicevolution:draconium_block:0>, <draconicevolution:draconic_block>, <draconicevolution:draconium_block:0>, <draconicevolution:draconic_block>, <draconicevolution:draconic_block>, <draconicevolution:draconic_block>, <draconicevolution:draconium_block:0>, <draconicevolution:draconic_block>, <draconicevolution:draconium_block:0>], [<advanced_solar_panels:crafting:5>, <ic2:quantum_leggings>, <extracells:storage.component:2>, <extrautils2:opinium:8>, <draconicevolution:awakened_core>, <extrautils2:opinium:8>, <extracells:storage.component:2>, <enderio:item_stellar_alloy_leggings>, <advanced_solar_panels:crafting:5>],[<advanced_solar_panels:crafting:5>, <avaritia:resource:6>, <extrautils2:opinium:8>, <advanced_solar_panels:crafting:5>, <draconicevolution:draconic_energy_core>, <advanced_solar_panels:crafting:5>, <extrautils2:opinium:8>, <avaritia:resource:6>, <advanced_solar_panels:crafting:5>],[<advanced_solar_panels:crafting:5>, <avaritia:resource:6>, <advanced_solar_panels:crafting:5>, null, <draconicevolution:wyvern_legs>, null, <advanced_solar_panels:crafting:5>, <avaritia:resource:6>, <advanced_solar_panels:crafting:5>],[<advanced_solar_panels:crafting:5>, <avaritia:resource:6>, <advanced_solar_panels:crafting:5>, null, null, null, <advanced_solar_panels:crafting:5>, <avaritia:resource:6>, <advanced_solar_panels:crafting:5>],[<advanced_solar_panels:crafting:5>, <avaritia:resource:6>, <advanced_solar_panels:crafting:5>, null, null, null, <advanced_solar_panels:crafting:5>, <avaritia:resource:6>, <advanced_solar_panels:crafting:5>],[<advanced_solar_panels:crafting:5>, <avaritia:resource:6>, <advanced_solar_panels:crafting:5>, null, null, null, <advanced_solar_panels:crafting:5>, <avaritia:resource:6>, <advanced_solar_panels:crafting:5>],[<advanced_solar_panels:crafting:5>, <projecte:item.pe_gem_armor_1>, <advanced_solar_panels:crafting:5>, null, null, null, <advanced_solar_panels:crafting:5>, <mysticalagriculture:supremium_leggings>, <advanced_solar_panels:crafting:5>],[<advanced_solar_panels:crafting:5>, <advanced_solar_panels:crafting:5>, <advanced_solar_panels:crafting:5>, null, null, null, <advanced_solar_panels:crafting:5>, <advanced_solar_panels:crafting:5>, <advanced_solar_panels:crafting:5>]]);

// 双足飞龙护腿
recipes.remove(<draconicevolution:wyvern_legs>);
mods.avaritia.ExtremeCrafting.addShaped("NAMEPLACEHOLDER9", <draconicevolution:wyvern_legs> * 1, [[<draconicevolution:draconium_block:0>, <draconicevolution:draconium_block:0>, <draconicevolution:draconium_block:0>, <draconicevolution:draconium_block:0>, <draconicevolution:draconium_block:0>, <draconicevolution:draconium_block:0>, <draconicevolution:draconium_block:0>, <draconicevolution:draconium_block:0>, <draconicevolution:draconium_block:0>], [<advanced_solar_panels:crafting:2>, <botania:terrasteellegs>, <enderio:block_alloy_endergy:3>, <draconicevolution:wyvern_core>, <extrautils2:opinium:8>, <draconicevolution:wyvern_core>, <enderio:block_alloy_endergy:3>, <mysticalagriculture:supremium_leggings>, <advanced_solar_panels:crafting:2>],[<advanced_solar_panels:crafting:2>, <extrautils2:opinium:8>, <enderio:block_alloy_endergy:3>, <advanced_solar_panels:crafting:2>, <draconicevolution:wyvern_energy_core>, <advanced_solar_panels:crafting:2>, <enderio:block_alloy_endergy:3>, <extrautils2:opinium:8>, <advanced_solar_panels:crafting:2>],[<advanced_solar_panels:crafting:2>, <avaritia:resource:4>, <advanced_solar_panels:crafting:2>, null, null, null, <advanced_solar_panels:crafting:2>, <avaritia:resource:4>, <advanced_solar_panels:crafting:2>],[<advanced_solar_panels:crafting:2>, <avaritia:resource:4>, <advanced_solar_panels:crafting:2>, null, null, null, <advanced_solar_panels:crafting:2>, <avaritia:resource:4>, <advanced_solar_panels:crafting:2>],[<advanced_solar_panels:crafting:2>, <avaritia:resource:4>, <advanced_solar_panels:crafting:2>, null, null, null, <advanced_solar_panels:crafting:2>, <avaritia:resource:4>, <advanced_solar_panels:crafting:2>],[<advanced_solar_panels:crafting:2>, <avaritia:resource:4>, <advanced_solar_panels:crafting:2>, null, null, null, <advanced_solar_panels:crafting:2>, <avaritia:resource:4>, <advanced_solar_panels:crafting:2>],[<advanced_solar_panels:crafting:2>, <projecte:item.pe_rm_armor_1>, <advanced_solar_panels:crafting:2>, null, null, null, <advanced_solar_panels:crafting:2>, <enderio:item_end_steel_leggings>, <advanced_solar_panels:crafting:2>],[<advanced_solar_panels:crafting:2>, <advanced_solar_panels:crafting:2>, <advanced_solar_panels:crafting:2>, null, null, null, <advanced_solar_panels:crafting:2>, <advanced_solar_panels:crafting:2>, <advanced_solar_panels:crafting:2>]]);

// 神龙胸甲
recipes.remove(<draconicevolution:draconic_chest>);
mods.avaritia.ExtremeCrafting.addShaped("NAMEPLACEHOLDER10", <draconicevolution:draconic_chest> * 1, [[null, <draconicevolution:draconium_block:0>, <draconicevolution:draconium_block:0>, null, null, null, <draconicevolution:draconium_block:0>, <draconicevolution:draconium_block:0>, null], [<enderio:block_alloy_endergy:3>, <draconicevolution:draconic_block>, <enderio:block_alloy_endergy:3>, null, null, null, <enderio:block_alloy_endergy:3>, <draconicevolution:draconic_block>, <enderio:block_alloy_endergy:3>],[<draconicevolution:draconium_block:0>, <enderio:block_alloy_endergy:3>, <draconicevolution:draconium_block:0>, null, null, null, <draconicevolution:draconium_block:0>, <enderio:block_alloy_endergy:3>, <draconicevolution:draconium_block:0>],[null, <advanced_solar_panels:crafting:5>, <extrautils2:opinium:8>, <enderio:item_stellar_alloy_chestplate>, <mysticalagriculture:supremium_chestplate>, <projecte:item.pe_gem_armor_2>, <extrautils2:opinium:8>, <advanced_solar_panels:crafting:5>, null],[null, <advanced_solar_panels:crafting:5>, <avaritia:resource:6>, <extracells:storage.component:2>, <draconicevolution:wyvern_chest>, <extracells:storage.component:2>, <avaritia:resource:6>, <advanced_solar_panels:crafting:5>, null],[null, <advanced_solar_panels:crafting:5>, <avaritia:resource:6>, <draconicevolution:draconic_block>, <draconicevolution:awakened_core>, <draconicevolution:draconic_block>, <avaritia:resource:6>, <advanced_solar_panels:crafting:5>, null],[null, <advanced_solar_panels:crafting:5>, <avaritia:resource:6>, <draconicevolution:draconic_block>, <draconicevolution:draconic_energy_core>, <draconicevolution:draconic_block>, <avaritia:resource:6>, <advanced_solar_panels:crafting:5>, null],[null, <advanced_solar_panels:crafting:5>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:6>, <advanced_solar_panels:crafting:5>, null],[null, null, <advanced_solar_panels:crafting:5>, <advanced_solar_panels:crafting:5>, <draconicevolution:draconic_block>, <advanced_solar_panels:crafting:5>, <advanced_solar_panels:crafting:5>, null, null]]);

// 双足飞龙胸甲
recipes.remove(<draconicevolution:wyvern_chest>);
mods.avaritia.ExtremeCrafting.addShaped("NAMEPLACEHOLDER11", <draconicevolution:wyvern_chest> * 1, [[null, <draconicevolution:draconium_block:0>, <draconicevolution:draconium_block:0>, null, null, null, <draconicevolution:draconium_block:0>, <draconicevolution:draconium_block:0>, null], [<draconicevolution:draconium_block:0>, <enderio:block_alloy_endergy:3>, <draconicevolution:draconium_block:0>, null, null, null, <draconicevolution:draconium_block:0>, <enderio:block_alloy_endergy:3>, <draconicevolution:draconium_block:0>],[<draconicevolution:draconium_block:0>, <draconicevolution:draconium_block:0>, <draconicevolution:draconium_block:0>, null, null, null, <draconicevolution:draconium_block:0>, <draconicevolution:draconium_block:0>, <draconicevolution:draconium_block:0>],[null, <advanced_solar_panels:crafting:2>, <avaritia:resource:4>, <enderio:item_end_steel_chestplate>, <mysticalagriculture:supremium_chestplate>, <ic2:nano_chestplate>, <avaritia:resource:4>, <advanced_solar_panels:crafting:2>, null],[null, <advanced_solar_panels:crafting:2>, <avaritia:resource:4>, <extrautils2:opinium:8>, <botania:terrasteelchest>, <extrautils2:opinium:8>, <avaritia:resource:4>, <advanced_solar_panels:crafting:2>, null],[null, <advanced_solar_panels:crafting:2>, <avaritia:resource:4>, <draconicevolution:draconium_block:0>, <draconicevolution:wyvern_core>, <draconicevolution:draconium_block:0>, <avaritia:resource:4>, <advanced_solar_panels:crafting:2>, null],[null, <advanced_solar_panels:crafting:2>, <avaritia:resource:4>, <draconicevolution:draconium_block:0>, <draconicevolution:wyvern_energy_core>, <draconicevolution:draconium_block:0>, <avaritia:resource:4>, <advanced_solar_panels:crafting:2>, null],[null, <advanced_solar_panels:crafting:2>, <avaritia:resource:4>, <extracells:storage.component:2>, <enderio:block_alloy_endergy:3>, <extracells:storage.component:2>, <avaritia:resource:4>, <advanced_solar_panels:crafting:2>, null],[null, null, <draconicevolution:draconium_block:0>, <draconicevolution:draconium_block:0>, <advanced_solar_panels:crafting:2>, <draconicevolution:draconium_block:0>, <draconicevolution:draconium_block:0>, null, null]]);

// 神龙靴
recipes.remove(<draconicevolution:draconic_boots>);
mods.avaritia.ExtremeCrafting.addShaped("NAMEPLACEHOLDER12", <draconicevolution:draconic_boots> * 1, [[null, <draconicevolution:draconium_block:0>, <draconicevolution:draconic_block>, <draconicevolution:draconium_block:0>, null, <draconicevolution:draconium_block:0>, <draconicevolution:draconic_block>, <draconicevolution:draconium_block:0>, null], [null, <advanced_solar_panels:crafting:5>, <mysticalagriculture:supremium_boots>, <advanced_solar_panels:crafting:5>, <draconicevolution:awakened_core>, <advanced_solar_panels:crafting:5>, <projecte:item.pe_gem_armor_0>, <advanced_solar_panels:crafting:5>, null],[null, <advanced_solar_panels:crafting:5>, <enderio:item_stellar_alloy_boots>, <advanced_solar_panels:crafting:5>, <draconicevolution:wyvern_boots>, <advanced_solar_panels:crafting:5>, <ic2:quantum_boots>, <advanced_solar_panels:crafting:5>, null],[<advanced_solar_panels:crafting:5>, <avaritia:resource:6>, <extracells:storage.component:2>, <advanced_solar_panels:crafting:5>, <extrautils2:opinium:8>, <advanced_solar_panels:crafting:5>, <extracells:storage.component:2>, <avaritia:resource:6>, <advanced_solar_panels:crafting:5>],[<advanced_solar_panels:crafting:5>, <avaritia:resource:6>, <draconicevolution:draconic_block>, <advanced_solar_panels:crafting:5>, <draconicevolution:draconic_energy_core>, <advanced_solar_panels:crafting:5>, <draconicevolution:draconic_block>, <avaritia:resource:6>, <advanced_solar_panels:crafting:5>],[<advanced_solar_panels:crafting:5>, <advanced_solar_panels:crafting:5>, <advanced_solar_panels:crafting:5>, <advanced_solar_panels:crafting:5>, <extrautils2:opinium:8>, <advanced_solar_panels:crafting:5>, <advanced_solar_panels:crafting:5>, <advanced_solar_panels:crafting:5>, <advanced_solar_panels:crafting:5>],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null]]);

// 双足飞龙靴
recipes.remove(<draconicevolution:wyvern_boots>);
mods.avaritia.ExtremeCrafting.addShaped("NAMEPLACEHOLDER13", <draconicevolution:wyvern_boots> * 1, [[null, <draconicevolution:draconium_block:0>, <enderio:block_alloy_endergy:3>, <draconicevolution:draconium_block:0>, null, <draconicevolution:draconium_block:0>, <enderio:block_alloy_endergy:3>, <draconicevolution:draconium_block:0>, null], [null, <advanced_solar_panels:crafting:2>, <projecte:item.pe_rm_armor_0>, <advanced_solar_panels:crafting:2>, <draconicevolution:wyvern_core>, <advanced_solar_panels:crafting:2>, <ic2:nano_boots>, <advanced_solar_panels:crafting:2>, null],[null, <advanced_solar_panels:crafting:2>, <botania:terrasteelboots>, <advanced_solar_panels:crafting:2>, <mysticalagriculture:supremium_boots>, <advanced_solar_panels:crafting:2>, <enderio:item_end_steel_boots>, <advanced_solar_panels:crafting:2>, null],[<advanced_solar_panels:crafting:2>, <avaritia:resource:4>, <extracells:storage.component:2>, <advanced_solar_panels:crafting:2>, <extrautils2:opinium:8>, <advanced_solar_panels:crafting:2>, <extracells:storage.component:2>, <avaritia:resource:4>, <advanced_solar_panels:crafting:2>],[<advanced_solar_panels:crafting:2>, <avaritia:resource:4>, <enderio:block_alloy_endergy:3>, <advanced_solar_panels:crafting:2>, <draconicevolution:wyvern_energy_core>, <advanced_solar_panels:crafting:2>, <enderio:block_alloy_endergy:3>, <avaritia:resource:4>, <advanced_solar_panels:crafting:2>],[<advanced_solar_panels:crafting:2>, <advanced_solar_panels:crafting:2>, <advanced_solar_panels:crafting:2>, <advanced_solar_panels:crafting:2>, <extrautils2:opinium:8>, <advanced_solar_panels:crafting:2>, <advanced_solar_panels:crafting:2>, <advanced_solar_panels:crafting:2>, <advanced_solar_panels:crafting:2>],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null],[null, null, null, null, null, null, null, null, null]]);

// 神龙剑
recipes.remove(<draconicevolution:draconic_sword>);
mods.avaritia.ExtremeCrafting.addShaped("NAMEPLACEHOLDER14", <draconicevolution:draconic_sword> * 1, [[null, null, null, null, null, null, null, <extrabotany:material:1>, <draconicevolution:draconic_energy_core>], [null, null, null, null, null, null, <extrabotany:material:1>, <draconicevolution:draconic_block>, <extrabotany:material:1>],[null, null, null, null, null, <extrabotany:material:1>, <draconicevolution:draconic_block>, <extrabotany:material:1>, null],[null, null, null, null, <extrabotany:material:1>, <enderio:item_stellar_alloy_sword>, <extrabotany:material:1>, null, null],[<avaritia:resource:5>, <draconicevolution:awakened_core>, null, <extrabotany:material:1>, <projecte:item.pe_rm_sword>, <extrabotany:material:1>, null, null, null],[null, <avaritia:resource:6>, <extrabotany:material:1>, <extrabotany:excaliber>, <extrabotany:material:1>, null, null, null, null],[null, <extracells:storage.component:2>, <draconicevolution:wyvern_sword>, <extrabotany:material:1>, null, null, null, null, null],[null, <extrabotany:material:1>, <extracells:storage.component:2>, <avaritia:resource:6>, <draconicevolution:awakened_core>, null, null, null, null],[<extrabotany:material:1>, null, null, null, <avaritia:resource:5>, null, null, null, null]]);

// 双足飞龙剑
recipes.remove(<draconicevolution:wyvern_sword>);
mods.avaritia.ExtremeCrafting.addShaped("NAMEPLACEHOLDER15", <draconicevolution:wyvern_sword> * 1, [[null, null, null, null, null, null, null, <draconicevolution:draconium_block:0>, <draconicevolution:wyvern_energy_core>], [null, null, null, null, null, null, <draconicevolution:draconium_block:0>, <enderio:block_alloy_endergy:3>, <draconicevolution:draconium_block:0>],[null, null, null, null, null, <draconicevolution:draconium_block:0>, <enderio:block_alloy_endergy:3>, <draconicevolution:draconium_block:0>, null],[null, null, null, null, <draconicevolution:draconium_block:0>, <enderio:item_stellar_alloy_sword>, <draconicevolution:draconium_block:0>, null, null],[<avaritia:resource:5>, <draconicevolution:wyvern_core>, null, <draconicevolution:draconium_block:0>, <botania:terrasword>, <draconicevolution:draconium_block:0>, null, null, null],[null, <avaritia:resource:6>, <draconicevolution:draconium_block:0>, <extrautils2:lawsword>, <draconicevolution:draconium_block:0>, null, null, null, null],[null, <extracells:storage.component:2>, <ic2:nano_saber>, <draconicevolution:draconium_block:0>, null, null, null, null, null],[null, <draconicevolution:draconium_block:0>, <extracells:storage.component:2>, <avaritia:resource:6>, <draconicevolution:wyvern_core>, null, null, null, null],[<draconicevolution:draconium_block:0>, null, null, null, <avaritia:resource:5>, null, null, null, null]]);

// 神龙铲
recipes.remove(<draconicevolution:draconic_shovel>);
mods.avaritia.ExtremeCrafting.addShaped("NAMEPLACEHOLDER16", <draconicevolution:draconic_shovel> * 1, [[null, null, null, null, null, null, <avaritia:resource:4>, <avaritia:resource:4>, <draconicevolution:draconic_energy_core>], [null, null, null, null, null, <avaritia:resource:4>, <avaritia:resource:6>, <draconicevolution:draconic_block>, <avaritia:resource:4>],[null, null, null, null, null, null, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:4>],[null, null, null, null, null, <projecte:item.pe_rm_shovel>, null, <avaritia:resource:4>, null],[null, null, null, <extrautils2:opinium:8>, <draconicevolution:wyvern_shovel>, null, null, null, null],[null, null, <extrabotany:material:1>, <draconicevolution:draconic_block>, <extrautils2:opinium:8>, null, null, null, null],[null, <extrabotany:material:1>, <extracells:storage.component:2>, <extrabotany:material:1>, null, null, null, null, null],[<advanced_solar_panels:crafting:2>, <enderio:block_alloy_endergy:3>, <extrabotany:material:1>, null, null, null, null, null, null],[<draconicevolution:awakened_core>, <advanced_solar_panels:crafting:2>, null, null, null, null, null, null, null]]);

// 双足飞龙铲
recipes.remove(<draconicevolution:wyvern_shovel>);
mods.avaritia.ExtremeCrafting.addShaped("NAMEPLACEHOLDER17", <draconicevolution:wyvern_shovel> * 1, [[null, null, null, null, null, null, <avaritia:resource:4>, <avaritia:resource:4>, <draconicevolution:wyvern_energy_core>], [null, null, null, null, null, <avaritia:resource:4>, <avaritia:resource:6>, <draconicevolution:wyvern_core>, <avaritia:resource:4>],[null, null, null, null, null, null, <avaritia:resource:6>, <avaritia:resource:6>, <avaritia:resource:4>],[null, null, null, null, null, <projecte:item.pe_rm_shovel>, null, <avaritia:resource:4>, null],[null, null, null, <extrautils2:opinium:8>, <botania:elementiumshovel>, null, null, null, null],[null, null, null, <draconicevolution:draconic_block>, <extrautils2:opinium:8>, null, null, null, null],[null, null, <enderio:block_alloy_endergy:3>, null, null, null, null, null, null],[<advanced_solar_panels:crafting:2>, <enderio:block_alloy_endergy:3>, null, null, null, null, null, null, null],[<draconicevolution:wyvern_core>, <advanced_solar_panels:crafting:2>, null, null, null, null, null, null, null]]);

// 神龙镐
recipes.remove(<draconicevolution:draconic_pick>);
mods.avaritia.ExtremeCrafting.addShaped("NAMEPLACEHOLDER18", <draconicevolution:draconic_pick> * 1, [[null, <extrabotany:material:1>, <extrabotany:material:1>, <extrabotany:material:1>, <extrabotany:material:1>, <extrabotany:material:1>, <extrabotany:material:1>, <extrabotany:material:1>, null], [<extrabotany:material:1>, <extrabotany:material:1>, <extrabotany:material:1>, <extrabotany:material:1>, <draconicevolution:draconic_energy_core>, <extrabotany:material:1>, <extrabotany:material:1>, <extrabotany:material:1>, <extrabotany:material:1>],[<draconicevolution:draconic_block>, <extrabotany:material:1>, null, <extrautils2:opinium:8>, <extracells:storage.component:2>, <extrautils2:opinium:8>, null, <extrabotany:material:1>, <draconicevolution:draconic_block>],[null, null, null, null, <projecte:item.pe_rm_pick>, null, null, null, null],[null, null, null, null, <draconicevolution:wyvern_pick>, null, null, null, null],[null, null, null, null, <enderio:item_stellar_alloy_pickaxe>, null, null, null, null],[null, null, null, null, <draconicevolution:draconic_block>, null, null, null, null],[null, null, null, null, <draconicevolution:draconic_block>, null, null, null, null],[null, null, null, null, <draconicevolution:awakened_core>, null, null, null, null]]);

// 双足飞龙镐
recipes.remove(<draconicevolution:wyvern_pick>);
mods.avaritia.ExtremeCrafting.addShaped("NAMEPLACEHOLDER19", <draconicevolution:wyvern_pick> * 1, [[null, <extrabotany:material:1>, <extrabotany:material:1>, <extrabotany:material:1>, <enderio:block_alloy_endergy:3>, <extrabotany:material:1>, <extrabotany:material:1>, <extrabotany:material:1>, null], [<extrabotany:material:1>, <extrabotany:material:1>, <enderio:block_alloy_endergy:3>, <extrabotany:material:1>, <draconicevolution:wyvern_energy_core>, <extrabotany:material:1>, <enderio:block_alloy_endergy:3>, <extrabotany:material:1>, <extrabotany:material:1>],[<draconicevolution:draconium_block:0>, <extrabotany:material:1>, null, <extrautils2:opinium:8>, <extracells:storage.component:2>, <extrautils2:opinium:8>, null, <extrabotany:material:1>, <draconicevolution:draconium_block:0>],[null, null, null, null, <advanced_solar_panels:crafting:2>, null, null, null, null],[null, null, null, null, <botania:terrapick>, null, null, null, null],[null, null, null, null, <enderio:item_stellar_alloy_pickaxe>, null, null, null, null],[null, null, null, null, <enderio:block_alloy_endergy:3>, null, null, null, null],[null, null, null, null, <enderio:block_alloy_endergy:3>, null, null, null, null],[null, null, null, null, <draconicevolution:wyvern_core>, null, null, null, null]]);

// 神龙弓
recipes.remove(<draconicevolution:draconic_bow>);
mods.avaritia.ExtremeCrafting.addShaped("NAMEPLACEHOLDER20", <draconicevolution:draconic_bow> * 1, [[null, null, null, <extrabotany:material:1>, <draconicevolution:awakened_core>, null, null, null, null], [null, null, <extrabotany:material:1>, null, <extrautils2:opinium:8>, null, null, null, null],[null, <extrabotany:material:1>, null, null, <extrautils2:opinium:8>, null, null, null, null],[<avaritia:resource:5>, <draconicevolution:wyvern_bow>, null, null, <extrautils2:opinium:8>, null, null, null, null],[<draconicevolution:draconic_block>, <extrautils2:compoundbow>, <enderio:item_capacitor_melodic>, null, <extrautils2:opinium:8>, null, null, null, null],[<avaritia:resource:5>, <botania:crystalbow>, null, null, <extrautils2:opinium:8>, null, null, null, null],[null, <extrabotany:material:1>, null, null, <extrautils2:opinium:8>, null, null, null, null],[null, null, <extrabotany:material:1>, null, <extrautils2:opinium:8>, null, null, null, null],[null, null, null, <extrabotany:material:1>, <draconicevolution:draconic_energy_core>, null, null, null, null]]);

// 双足飞龙弓
recipes.remove(<draconicevolution:wyvern_bow>);
mods.avaritia.ExtremeCrafting.addShaped("NAMEPLACEHOLDER21", <draconicevolution:wyvern_bow> * 1, [[null, null, null, <enderio:block_alloy_endergy:3>, <draconicevolution:wyvern_core>, null, null, null, null], [null, null, <enderio:block_alloy_endergy:3>, null, <extrautils2:opinium:8>, null, null, null, null],[null, <enderio:block_alloy_endergy:3>, null, null, <extrautils2:opinium:8>, null, null, null, null],[<extrabotany:material:1>, <enderio:item_capacitor_melodic>, null, null, <extrautils2:opinium:8>, null, null, null, null],[<avaritia:resource:5>, <extrautils2:compoundbow>, null, null, <extrautils2:opinium:8>, null, null, null, null],[<extrabotany:material:1>, <enderio:item_capacitor_melodic>, null, null, <extrautils2:opinium:8>, null, null, null, null],[null, <enderio:block_alloy_endergy:3>, null, null, <extrautils2:opinium:8>, null, null, null, null],[null, null, <enderio:block_alloy_endergy:3>, null, <extrautils2:opinium:8>, null, null, null, null],[null, null, null, <enderio:block_alloy_endergy:3>, <draconicevolution:wyvern_energy_core>, null, null, null, null]]);

// 加速火把
recipes.remove(<torcherino:blocktorcherino>);
mods.avaritia.ExtremeCrafting.addShaped("NAMEPLACEHOLDER22", <torcherino:blocktorcherino> * 1, [[null, <extrabotany:material:1>, <thermalfoundation:storage_alloy:7>, <enderio:block_alloy_endergy:3>, <enderio:block_alloy_endergy:3>, <enderio:block_alloy_endergy:3>, <thermalfoundation:storage_alloy:7>, <extrabotany:material:1>, null], [null, <extrabotany:material:1>, <extrabotany:material:1>, <ic2:crafting:4>, <enderio:item_capacitor_totemic>, <ic2:crafting:4>, <extrabotany:material:1>, <extrabotany:material:1>, null],[null, null, <extrabotany:material:1>, <ic2:crafting:4>, <advanced_solar_panels:crafting:12>, <ic2:crafting:4>, <extrabotany:material:1>, null, null],[null, null, <mekanism:controlcircuit:3>, <extrautils2:opinium:8>, <mysticalagradditions:insanium:1>, <extrautils2:opinium:8>, <mekanism:controlcircuit:3>, null, null],[null, null, <ic2:crafting:4>, <mysticalagradditions:insanium:1>, <advanced_solar_panels:crafting:13>, <mysticalagradditions:insanium:1>, <ic2:crafting:4>, null, null],[null, null, null, <extrautils2:opinium:8>, <mysticalagradditions:insanium:1>, <extrautils2:opinium:8>, null, null, null],[null, null, null, <mekanism:controlcircuit:3>, <botania:storage:1>, <mekanism:controlcircuit:3>, null, null, null],[null, null, null, null, <botania:storage:1>, null, null, null, null],[null, null, null, null, <avaritia:resource:5>, null, null, null, null]]);

