// File generated by MineTweakerRecipeMaker
//                     READ THIS HEADER BEFORE EDITING ANYTHING
// ================================================================================
//     This file is read and changed by the mod.
//     If you remove/edit any of the markers, IT WILL STOP WORKING!
//     If you want to make manual edits, make a backup of this file!
//     Markers look like this: "//#MARKER something"
//     They indicate where calls should be placed, so that MineTweaker does them in the correct order.
//     Removes come first, then stuff is added.
// ================================================================================
//

// ================================================================================
//#MARKER REMOVE
recipes.remove(<extrautils2:angelring:5>);
recipes.remove(<extrautils2:angelring:4>);
recipes.remove(<extrautils2:angelring:3>);
recipes.remove(<extrautils2:angelring:2>);
recipes.remove(<extrautils2:angelring>);
recipes.remove(<extrautils2:opinium:4>);
recipes.remove(<extrautils2:opinium:2>);
recipes.remove(<extrautils2:opinium:1>);
recipes.remove(<extrautils2:opinium:3>);
recipes.remove(<extrautils2:opinium>);
recipes.remove(<extrautils2:opinium:7>);
recipes.remove(<extrautils2:opinium:8>);
recipes.remove(<extrautils2:opinium:6>);
recipes.remove(<extrautils2:opinium:5>);

// ================================================================================
//#MARKER REMOVE SHAPELESS

// ================================================================================
//#MARKER REMOVE SHAPED

// ================================================================================
//#MARKER ADD

// ================================================================================
//#MARKER ADD SHAPELESS

// ================================================================================
//#MARKER ADD SHAPED
recipes.addShaped(<extrautils2:opinium:8>, [[<avaritia:resource:4>, <avaritia:resource:5>, <ore:ingotCosmicNeutronium>], [<extrautils2:opinium:7>, <advanced_solar_panels:crafting:13>, <extrautils2:opinium:7>], [<ore:ingotCosmicNeutronium>, <avaritia:resource:5>, <ore:ingotCosmicNeutronium>]]);
recipes.addShaped(<extrautils2:opinium:7>, [[<ore:ingotCosmicNeutronium>, <advanced_solar_panels:crafting:13>, <avaritia:resource:4>], [<extrautils2:opinium:6>, <ore:craftingMTCore>, <extrautils2:opinium:6>], [<avaritia:resource:4>, <advanced_solar_panels:crafting:13>, <ore:ingotCosmicNeutronium>]]);
recipes.addShaped(<extrautils2:opinium:6>, [[<mekanism:controlcircuit:3>, <advanced_solar_panels:crafting:5>, <mekanism:controlcircuit:3>], [<extrautils2:opinium:5>, <advanced_solar_panels:crafting:13>, <extrautils2:opinium:5>], [<mekanism:controlcircuit:3>, <advanced_solar_panels:crafting:5>, <mekanism:controlcircuit:3>]]);
recipes.addShaped(<extrautils2:opinium:5>, [[<ore:gaiaIngot>, <minecraft:experience_bottle>, <ore:gaiaIngot>], [<extrautils2:opinium:4>, <minecraft:chorus_flower>, <extrautils2:opinium:4>], [<ore:gaiaIngot>, <minecraft:experience_bottle>, <ore:gaiaIngot>]]);
recipes.addShaped(<extrautils2:opinium:4>, [[<botania:storage:1>, <extrautils2:opinium:3>, <botania:storage:1>], [<botania:storage:4>, <minecraft:emerald_block>, <botania:storage:4>], [<botania:storage:1>, <extrautils2:opinium:3>, <botania:storage:1>]]);
recipes.addShaped(<extrautils2:opinium:3>, [[<botania:rune:5>, <extrautils2:opinium:2>, <botania:rune:6>], [<botania:rune:4>, <botania:rune:12>, <botania:rune:7>], [<botania:rune:15>, <extrautils2:opinium:2>, <botania:rune:11>]]);
recipes.addShaped(<extrautils2:opinium:2>, [[<botania:storage:4>, <extrautils2:opinium:1>, <botania:storage:4>], [<botania:storage:2>, <botania:storage:3>, <botania:storage:2>], [<botania:storage:4>, <extrautils2:opinium:1>, <botania:storage:4>]]);
recipes.addShaped(<extrautils2:opinium:1>, [[<botania:storage>, <extrautils2:opinium>, <botania:storage>], [<minecraft:iron_block>, <ore:blockGold>, <minecraft:iron_block>], [<botania:storage>, <extrautils2:opinium>, <botania:storage>]]);
recipes.addShaped(<extrautils2:opinium>, [[<botania:storage>, <extrautils2:ingredients:4>, <botania:storage>], [<extrautils2:ingredients:4>, <minecraft:iron_block>, <extrautils2:ingredients:4>], [<botania:storage>, <extrautils2:ingredients:4>, <botania:storage>]]);

